# 変数

## 変数の宣言

[１章の変数のセクション](010_outline.Rmd)で述べたようにC++では変数を使う前に必ず宣言しなければいけません。

## 変数の型

C++で利用できる基本的なスカラー値の型には以下があります。ベクトルなど複数のスカラー値が組み合わさったデータ構造についてはデータ構造とアルゴリズムのセクションを参照してください。



| 説明 | 型 | 値の例 | 値の範囲 |
|:-----------:|:------------:|:------------:|:------------|
|論理値 | bool | true | true または false     |
|文字 | char | 'a' '\n'|英数記号文字リテラル（ASCII文字）|
|文字列|char*| "abcd\n"|ASCII文字の列|
|文字列|std::string|"abcd\n", u8"あいうえお"|ASCII文字の列、UTF8のマルチバイト文字列|
| 整数（符号あり）|int | 1 |-2147483648 ~ 2147483647|
| 整数（符号あり）|long | 1 |-2147483648 ~ 2147483647|
| 整数（符号あり）|long long | 1 |-9223372036854775808 ~ 9223372036854775807|
| 整数（符号なし）|unsigned int | 1 | 0 ~ 4294967295|
| 整数（符号なし）|unsigned long | 1 |0 ~ 4294967295|
| 整数（符号なし）|unsigned long long | 1 |0 ~ 18446744073709551615|
| 浮動小数点数（単精度）|float| 1.0 | -3.40282e+38 ~ 3.40282e+38|
| 浮動小数点数（倍精度）| 1.0 |double| -1.79769313486232e+308 ~ 1.79769313486232e+308|
| 浮動小数点数（拡張倍精度）| 1.0 |double| -1.79769313486232e+308 ~ 1.79769313486232e+308|

| be         |          be |      be      |
| left       |       right |    center    |
| aligned    |     aligned |   aligned    |


C++では同じ整数でも複数の型が存在していますが、それらの違いは扱える値の範囲が異なる点です。広い範囲の値を扱うためにはより大きなメモリ容量が必要となるので、処理に必要な値の範囲に合わせて変数の型を適切に選択することでメモリを効率よく使うことができますし、処理速度も速くなることが期待されます。

しかし、R/Rcppの整数ベクトルの要素の値は int 型、実数ベクトルの要素の値は double 型であるので、その範囲外の値をRのベクトルに渡しても正しく扱うことはできません。

ちなみに、ある型が扱える値の範囲（型が使用するメモリ容量）は処理系（コンパイラの種類; gcc, clang, visual c++ など）により異なります。このドキュメントでは Rcpp が対応している gcc, clang における値の範囲で表記します。

整数型の値の範囲は [climits](https://cpprefjp.github.io/reference/climits.html) ヘッダに、浮動小数点数型の値の範囲は[cfloat](https://cpprefjp.github.io/reference/cfloat.html)ヘッダに定義されています。

Rcpp でそれを簡単に確認するには、例えばRのコンソールに以下のように入力します。

```
> Rcpp::evalCpp("INT_MAX")
[1] 2147483647
> Rcpp::evalCpp("DBL_MAX")
[1] 1.797693e+308
```

メモ：std::numeric_limitsクラスを利用しても同じことができる。

```
> Rcpp::evalCpp("std::numeric_limits<int>::max()")
[1] 2147483647
```
